config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  #resources :user_signed_in

  resources :users do
    resources :cooks
    resources :ratings
  end

  resource :session, only: [:new, :destroy, :create]

  resources :recipes do
    resources :reviews, only: [:create, :destroy]
  end

  # resources :ratings

  resources :orders, only: [:create, :destroy]


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'users/:id/dashboard', to: 'users#dashboard', as: :dashboard_user

  get 'users/:id/cooks', to: 'users#cooks', as: :cooks_user

  patch 'users/:id/review/:id/approve', to: 'users#approve', as: :approve

  get 'search', to: 'searches#show'


end

app/models/recipe.rb
class Recipe < ApplicationRecord

    has_many :reviews, dependent: :destroy
    has_many :orders, dependent: :destroy

    belongs_to :user

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]
  # GET /recipes
  def index
    @recipes = Recipe.all
    @review = Review.new
  end

  # GET /recipes/1
  def show
    @review = Review.new
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." 
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if can? :crud, @recipe
      if @recipe.update(recipe_params)
        redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." 
      else
        render :edit, status: :unprocessable_entity 
      end
    else
      redirect_to recipe_url(@recipe), notice: "Not Authorized to edit recipe" 
    end
  end

  # DELETE /recipes/1
  def destroy
    if can? :destroy, @recipe
      @recipe.destroy
        redirect_to recipes_url, notice: "Recipe was successfully destroyed." 
    else
        redirect_to recipe_url(@recipe), notice: "Not authorized to delete this recipe." 
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:title, :description, :ingredients)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with model: @recipe, data:{ turbo:false } do |form| %>
  <% if @recipe.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% @recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-outline mb-4">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control form-control-lg" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :image_url %>
    <%= form.text_area :image_url, class: "form-control form-control-lg" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control form-control-lg" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :ingredients  %>
    <%= form.text_area :ingredients, class: "form-control form-control-lg" %>
  </div>

  <div>
    <%= form.submit%>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Title:</strong>
    <%= recipe.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Ingredients:</strong>
    <%= recipe.ingredients %>
  </p>

</div>

app/views/recipes/edit.html.erb
<section class="" style="background: url(https://images.pexels.com/photos/511763/pexels-photo-511763.jpeg?cs=srgb&dl=pexels-pixabay-511763.jpg&fm=jpg);">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
                <h2 class="text-uppercase text-center mb-3">Edit Meal</h2>
                
                <%= render "form" %>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<br>

<div class="d-flex justify-content-center my-4">
  <a class="btn btn-dark text-uppercase p-3" href="<%= @recipe %>"id="sign-up-btn">Show this recipe</a> |
  <a class="btn btn-dark text-uppercase p-3" href="<%= recipes_path %>"id="sign-up-btn">return to recipes</a>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  
<div class="flex-container col-16  d-flex justify-content-center m-0">

  <% @recipes.each do |recipe| %>
  
    
      
        <div class="item-container m-3">
            
          <div class="card m3 index-card h-100">
          <% if recipe.image_url %>
            <%= image_tag recipe.image_url, class:"show-image img-fluid" %>
          <% end %>
          <div class="card-body">
          <div class="mb-1 d-flex justify-content-center">
            <h4><%= link_to recipe.title, recipe_path(recipe), class:"card-title mt-2 title-list-item text-dark fw-bold"%></h4>
            </div>
            <div>
             <%= recipe.description %>
             </div>
          </div>
        </div>
        
      </div>
    
  <% end %>
</div>
</div>


<%= link_to "New recipe", new_recipe_path %>


   

app/views/recipes/new.html.erb
<section class="bg-image"
  style="background-image: url('https://th.bing.com/th/id/OIP.d6s9jZ3ee_EC5de2WcqPwwHaE8?pid=ImgDet&rs=1');" >
<div class="mask d-flex align-items-center h-100 gradient-custom-3 pb-0">
    <div class="container h-100 pb-0">
      <div class="container row d-flex justify-content-center align-items-center h-100 pb-0">
        <div class="container col-12 col-md-9 col-lg-7 col-xl-6 pb-0">
          <div class="card m-4" style="">
            <div class="card-body px-5 pt-5">
               
             <h2 class="text-uppercase text-center mb-5">Create a Meal</h2>
                <%= render "form", recipe: @recipe %>
                </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<br>

<div class="d-flex justify-content-center my-4">
  <a class="btn btn-dark text-uppercase p-3" href="<%= recipes_path %>"id="sign-up-btn">return to recipes</a>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mt-5">
  <div class="card">
    <div class="row">
      <div class="col-md-6 col-lg-4">
        <div class="p-3 p-md-4 p-lg-6 pe-md-0">
          <div class="show-image-container ">
            <% if @recipe.image_url %>
              <%= image_tag @recipe.image_url, class:"show-image img-fluid" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-8">
        <div class="p-3 p-md-4 p-lg-6 ps-md-0">
          <h2 class="card-title"><strong><%= @recipe.title %></strong></h2>
          <small>Created by Chef <%= @recipe.user.last_name %></small>
          <div class="mb-3"><%= @recipe.description %></div>
            <a href="<%#=recipe_orders_path(@recipe, @user) %>" class="btn btn-secondary">Order Now</a>

          </div>
        </div>
      </div>
    </div>
  <div>
  </div>

  <div>
  <br>
  <h3>Reviews</h3>   
            <% @recipe.reviews.each do |review| %>
                <br>
                <%= review.body %> 
                <br>
                Created <%= time_ago_in_words(review.created_at) %> ago
                <br>
            <% end %>

  <p>
  <%= @review.errors.full_messages.join(', ') %>
  <% if user_signed_in? %>
    <%= form_for [@recipe, @review] do |f| %>
        <%= f.text_area :body %>
        <br>
        <%= f.submit%>
    <% end %>
  </p>
  </div>

  <div class="d-flex justify-content-center my-4">
    <% if can? :crud, @recipe %>
      <a class="btn btn-dark text-uppercase p-3" href="<%= edit_recipe_path(@recipe)%>"id="sign-up-btn">Edit this recipe</a> | 
      <%= button_to "Destroy this recipe", recipe_path(@recipe), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}}, class:"btn btn-dark text-uppercase p-3" %>|
      <a class="btn btn-dark text-uppercase p-3" href="<%= recipes_path %>"id="sign-up-btn">Back to Recipe</a> 

    <% end %>
  <% else %>
  </p>
  </div>

  <div class="d-flex justify-content-center my-4">
  <a class="btn btn-dark text-uppercase p-3" href="<%= recipes_path %>"id="sign-up-btn">Back to Recipe</a> 
  <% end %>
  
  </div>
</div>