config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  #resources :user_signed_in

  resources :users do
    resources :cooks
    resources :ratings
  end

  resource :session, only: [:new, :destroy, :create]

  resources :recipes do
    resources :reviews, only: [:create, :destroy]
  end

  # resources :ratings

  resources :orders, only: [:create, :destroy]


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'users/:id/dashboard', to: 'users#dashboard', as: :dashboard_user

  get 'users/:id/cooks', to: 'users#cooks', as: :cooks_user

  patch 'users/:id/review/:id/approve', to: 'users#approve', as: :approve

  get 'search', to: 'searches#show'


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :recipes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  # User making a rating
  has_many :ratings, dependent: :destroy

  

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users
  def index
    @users = User.all
    @cooks = Cook.all
    
  end

  # GET /users/1
  def show
    @cooks = Cook.all
    @recipes = Recipe.all
    @ratings = Rating.all
  end

  def dashboard
    @user = current_user
    @recipes = @user.recipes
    #redirect_to 
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @users = User.all
     @user = current_user
  end


#If that above gives errors, try the below:
  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    # @user = current_user

    if @user.update(user_params)
      redirect_to user_url(@user), notice: "User was successfully updated." 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
      redirect_to users_url, notice: "User was successfully destroyed." 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(
        :first_name, 
        :last_name, 
        :email, 
        :password, 
        :password_confirmation, 
        :address, 
        :phone, 
        :is_cook)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<section class="bg-image"
  style="background-image: url('https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');" >
<div class="mask d-flex align-items-center h-100 gradient-custom-3 pb-0">
    <div class="container h-100 pb-0">
      <div class="container row d-flex justify-content-center align-items-center h-100 pb-0">
        <div class="container col-12 col-md-9 col-lg-7 col-xl-6 pb-0">
          <div class="card m-4" style="">
            <div class="card-body px-5 pt-5">

            <%if @user.id %>
                  <h2 class="text-uppercase text-center mb-5">Update your account</h2>
                <% else %>
                  <h2 class="text-uppercase text-center mb-5">Sign Up</h2>
            <% end %>

            <% if user.errors.any? %>
            <div style="color: red">
            <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
            <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
            </ul>
            </div>
            <% end %>
            <div class="form-outline mb-4">

            <%#= form_with(model: user) do |form| %>
          <%= form_for @user do |form| %>
            <div class="form-outline mb-4">
              <%= form.label :first_name, class: "form-label" %>
              <%= form.text_field :first_name, class: "form-control form-control-lg" %>
            </div>

            <div class="form-outline mb-4">
              <%= form.label :last_name, class: "form-label" %>
              <%= form.text_field :last_name, class: "form-control form-control-lg" %>
            </div>

            <div class="form-outline mb-4">
              <%= form.label :email, class: "form-label" %>
              <%= form.text_field :email, class: "form-control form-control-lg" %>
            </div>

            <div class="form-outline mb-4">
              <%= form.label :password, class: "form-label" %>
              <%= form.password_field :password, class: "form-control form-control-lg" %>
            </div>
            <div class="form-outline mb-4">
              <%= form.label :password_confirmation, class: "form-label" %>
              <%= form.password_field :password_confirmation, class: "form-control form-control-lg" %>
            </div>

            <div class="form-outline mb-4">
              <%= form.label :address, class: "form-label" %>
              <%= form.text_field :address, class: "form-control form-control-lg" %>
            </div>

            <div class="form-outline mb-4">
              <%= form.label :phone, "Phone Number", class: "form-label" %>
              <%= form.text_field :phone, class: "form-control form-control-lg" %>
            </div>

            <div class="form-outline mb-4">
              <%= form.label :is_cook, "Are you a cook?", class: "form-label" %>
              <%= form.check_box :is_cook, :checked => false %>
            </div>

            <div class="form-outline mb-4">
              <%= form.submit %>
            </div>
          <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">

  <p>
    <%if user.is_cook? %>
    <strong>Chef Account</strong>
    <% else %>
    <strong>Account</strong>
    <% end %>
  </p>
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= user.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>


</div>

app/views/users/admin.html.erb
  <%# for cooks %>
<% if user_signed_in? && user.is_cook? %>
    <%# pending reviews %>
    <h3>Pending Reviews <h3>
    <% @user.reviews.each do |review| %>
        <% if review.pending? %>
            <%= review.body %>
            Created <%= time_ago_in_words(review.created_at) %> ago 
            <%= button_to 'Approve',  user_review_path(@user.id, review.id), method: :approve, data: {confirm: "Are you sure"} %>
            <%= button_to 'Deny',  user_review_path(@user.id, review.id), method: :deny, data: {confirm: "Are you sure"}  %>
        <% end %>
    <% end %>
    <%# orders %>
    <% @user.orders.each do |order| %>
        <% if order.pending? %>
            <%= order.body %>
            Created <%= time_ago_in_words(order.created_at) %> ago 
            <%= button_to 'Accept',  user_order_path(@user.id, order.id), method: :accept, data: {confirm: "Are you sure"}
            <%= button_to 'Decline',  user_order_path(@user.id, order.id),method: :decline, data: {confirm: "Are you sure"} %>
        <% end %>
    <% end %>
    <%# all meals/edit - here or just on cook show page with edit visible to just the cook? %>
    <% @user.meals.each do |meal| %>
            <% if meal.pending? %>
                <%= meal.body %>
                Created <%= time_ago_in_words(meal.created_at) %> ago 
                <% if can? :crud, meal%>
                    <%= button_to "Edit", edit_meal_path(@meal), method: :get %>%
                <% end %>
            <% end %>

<% else %>
    <%# for non-cooks %>
    <% if user_signed_in?%>
    <h3>Pending Reviews <h3>
        <% @user.reviews.each do |review| %>
            <% if review.pending? %>
                <%= review.body %>
                Created <%= time_ago_in_words(review.created_at) %> ago 
                <% if can? :crud, review %>
                    <%= button_to "Edit", edit_review_path(@review), method: :get %>%
                <% end %>
        <% end %>
        <h3>Reviews <h3>
        <% @user.reviews.each do |review| %>
            <% if !review.pending? %>
                <%= review.body %>
                Created <%= time_ago_in_words(review.created_at) %> ago 
                <% if review.approved? %>
                <p style = "color: green"> Review Approved <p>
                <% else %>
                <p style = "color: red"> Review Denied <p>
            <% end %>
        <% end %>  
    <% end %>  
<% end %>

app/views/users/dashboard.html.erb
  <%# for cooks %>
<% if user_signed_in? && @user.is_cook? %>
    <%# pending reviews %>
    <h3>Pending Reviews </h3>
    <% @user.reviews.each do |review| %>
        <% if review.pending? %>
            <%= review.body %>
            <br>
            Created <%= time_ago_in_words(review.created_at) %> ago 
            <%= button_to 'Approve', user_path(@user.id, review.id), method: :approve, data: {confirm: "Are you sure"} %>
            <%= button_to 'Deny', user_path(@user.id, review.id), method: :deny, data: {confirm: "Are you sure"}  %>
        <% end %>
    <% end %>
    <%# orders %>
    <h3>Orders </h3>
    <% @user.orders.each do |order| %>
        <% if (order.pending?) %>
            <%= order.body %>
            <br>
            Created <%= time_ago_in_words(order.created_at) %> ago 
            <%= button_to 'Accept',  user_order_path(@user.id, order.id), method: :accept, data: {confirm: "Are you sure"}  %>

            <%= button_to 'Decline',  user_order_path(@user.id, order.id),method: :decline, data: {confirm: "Are you sure"} %>
        <% end %>
    <% end %>
    <h3>My Meals </h3>
    <%# all meals/edit - here or just on cook show page with edit visible to just the cook? %>
    <% @user.recipes.each do |r| %>
        <%= link_to r.title,  edit_recipe_path(r.id), method: :get %>
    <% end %>
<% else %>
    <%# for non-cooks %>
    <% if user_signed_in?%>
        <h3>Pending Reviews </h3>
        <% @user.reviews.each do |review| %>
            <% if review.pending? %>
                <%= review.body %>
                <br>
                Created <%= time_ago_in_words(review.created_at) %> ago 
               <p style = "color: orange"> Review Pending <p>
                <%# if can? :crud, review %>
                    <%#= button_to "Edit", edit_recipe_review_path(@recipe.id, @review.id), method: :get %>
                <%# end %>
            <% end %>
        <% end %>  
        <h3>Reviews </h3>
        <% @user.reviews.each do |review| %>
            <% if !review.pending? %>
                <% if review.approved? %>
                    <%= review.body %>
                    <p style = "color: green"> Review Approved <p>
                <% else %>
                    <%= review.body %>
                    <p style = "color: red"> Review Denied <p>
                <% end %>
            <% end %>  
        <% end %>  

     <% end %> 

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div class="d-flex justify-content-center my-4">
  <a class="btn btn-dark text-uppercase p-3" href="<%= @users %>"id="sign-up-btn">Edit the user</a> |
  <a class="btn btn-dark text-uppercase p-3" href="<%= users_path %>"id="sign-up-btn">return to users</a>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<%#= render @users %>
 <%#= if @users.is_cook? %>
  <%#= @user.first_name %>
<%# end %>


<h1>Users</h1>


<div id="users">

<div class="flex-container col-16  d-flex justify-content-center m-0">

  <% @users.each do |user| %>

  <div class="item-container m-3">
            
          <div class="card m3 index-card h-100">
    <%#= render @users %>
    <% if user.is_cook? %>
       <%= user.first_name %>
      <% end %>
       <div class="card-body">
          <div class="mb-1 d-flex justify-content-center">
    <p>
      <%= link_to "Show this user", user, class:"card-title mt-2 title-list-item text-dark fw-bold" %>
    </p>
    </div>

    </div>
        </div>
        
      </div>
  
    
  <% end %>
</div>
</div>

  <%= link_to "Back to users", users_path, class:"btn btn-outline-dark btn-lg btn-block" %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>
<section class="" style="background: url(https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8Y2hlZnxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80);">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
<h2 class="text-uppercase text-center mb-3">Showing Cook</h2>

<%= render @user %>

<%# @ratings.each do |rating| %>

    <%# if cook.user_id == @user %>
    <p> Chef Rating: 5 </p>
     <%#= @rating.user_id %>
    <br>
    <%# end %>
  <%# end %>


  <% @recipes.each do |recipe| %>

    <% if recipe.user == @user%>
     <%= render recipe %>

      <small>
        Created by Chef <%= recipe.user.last_name %>
      </small>

    <br>
    <% end %>
  <% end %>

<div>
  <%= link_to "Back to Chefs", users_path %>



                </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>



<div class="d-flex justify-content-center my-4">
  <a class="btn btn-dark text-uppercase p-3" href="<%= edit_user_path(@user) %>"id="sign-up-btn">Edit the user</a> |
  <a class="btn btn-dark text-uppercase p-3" href="<%= users_path %>"id="sign-up-btn">return to users</a>
</div>