config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  #resources :user_signed_in

  resources :users do
    resources :cooks
    resources :ratings
  end

  resource :session, only: [:new, :destroy, :create]

  resources :recipes do
    resources :reviews, only: [:create, :destroy]
  end

  # resources :ratings

  resources :orders, only: [:create, :destroy]


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'users/:id/dashboard', to: 'users#dashboard', as: :dashboard_user

  get 'users/:id/cooks', to: 'users#cooks', as: :cooks_user

  patch 'users/:id/review/:id/approve', to: 'users#approve', as: :approve

  get 'search', to: 'searches#show'


end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:

    user ||= User.new #guest user (not logged in)

    #if user.admin? temp update as we do not have admin column in db yet
    if user.present?
      can :manage, :all
    else
      can :read, :all
    end

    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

    #:read is an alias for :index and :show
    #alias_action :index, :show, :to => :read

    alias_action :create, :read, :update, :delete, :to => :crud


    can :crud, Order do |order|
      user == order.user
    end

    can :crud, Rating do |rating|
      user == rating.user #|| answer.question.user
    end

    can :crud, Review do |review|
      user == review.user #|| answer.question.user
    end

    can :crud, Recipe do |recipe|
      user == recipe.user
    end

    can :create, Rating do |rating| #maybe should be |recipe| instead?
      user.persisted? && recipe.user != user
      #checks if the user is in the database
      #does not allow the recipe owner to like their own recipe
    end

    can :create, Review do |review| #maybe should be |recipe| instead?
      user.persisted? && recipe.user != user
      #checks if the user is in the database
      #does not allow the recipe owner to like their own recipe
    end
  

    can :destroy, Rating do |rating|
      rating.user == user || recipe.user
    end

    can :destroy, Review do |review|
      review.user == user || recipe.user
    end


  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cook.rb
class Cook < ApplicationRecord
  belongs_to :user
  has_many :ratings, dependent: :destroy
  has_many :raters, through: :ratings, source: :user, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :recipe
end

app/models/rating.rb
class Rating < ApplicationRecord

  # Associations

  belongs_to :user
  belongs_to :cook

  

  # Validations

  validates(
    :cook_id,
    uniqueness: {
      scope: :user_id,
      message: "Has already been rated"
      }
    )
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord

    has_many :reviews, dependent: :destroy
    has_many :orders, dependent: :destroy

    belongs_to :user

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  private
 
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :recipes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  # User making a rating
  has_many :ratings, dependent: :destroy

  

  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user!, only:[:edit, :update, :destroy]
  before_action :set_recipe, only: %i[ show edit update destroy ]
  # GET /orders
  def index
    @orders = Order.all
  end

  # GET /orders/1 
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  def create
    @order = Order.new(order_params)
    @order.recipe = @recipe
    @order.user = current_user
    if @order.save
      redirect_to order_url(@order), notice: "Order was successfully created." 

    else
      render :new, status: :unprocessable_entity 
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
    redirect_to order_url(@order), notice: "Order was successfully updated." 
    
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
       redirect_to orders_url, notice: "Order was successfully destroyed." 
  end

  def approve
      @order.update_attribute(:pending?, false)
      @order.update_attribute(:approved?, true)
      redirect_to admin_path,  notice: "Order was Approved."
  end

  def deny
    @order.update_attribute(:pending?, false)
    @order.update_attribute(:approved?, false)
    redirect_to admin_path,  notice: "Order was denied."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:payment_type, :delivery_type, :delivery_date)
    end

    def authorize_user!
      redirect_to root_path, alert: "Not authorized!" unless can?(:crud, @order)
    end

    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

   
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users
  def index
    @users = User.all
    @cooks = Cook.all
    
  end

  # GET /users/1
  def show
    @cooks = Cook.all
    @recipes = Recipe.all
    @ratings = Rating.all
  end

  def dashboard
    @user = current_user
    @recipes = @user.recipes
    #redirect_to 
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @users = User.all
     @user = current_user
  end


#If that above gives errors, try the below:
  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    # @user = current_user

    if @user.update(user_params)
      redirect_to user_url(@user), notice: "User was successfully updated." 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
      redirect_to users_url, notice: "User was successfully destroyed." 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(
        :first_name, 
        :last_name, 
        :email, 
        :password, 
        :password_confirmation, 
        :address, 
        :phone, 
        :is_cook)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="bg-secondary">
         
            <div class="row d-flex justify-content-center text-center p-2">
                <div class="col-lg-3 col-md-6 col-sm-12">
                            <%= image_tag "https://cdn-icons-png.flaticon.com/512/1980/1980788.png", id: 'logo-footer', class: "mt-3", style:"width: 3rem"%> 
                    <h2 class="text-light fw-bold mt-3">Fast Food</h2>
                    
                </div>
            </div>

            <div class="container p-4">

            <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-12 text-light">
                        <h4 class="mt-3 text-light fw-bold">Contact Us</h1>
                        <p class="text-light">Vancouver, BC.</p>
                        <p><a class="text-light" href="mailto:hello@delish.ca">hello@fastfood.ca</a></p>
                        <p><a class="text-light" href="tel:1-800-888-8888">1-800-888-8888</a></p>
                    </div>

                    <div class="col-lg-3 col-md-6 col-sm-12 text-light">
                        
                            <p><a style="color: #3b5998;" href="#!" role="button">
                                <i class="fab fa-facebook-f fa-lg"></i>
                            </a>
                            </p>
                        
                            <a
                                class="btn btn-link btn-floating btn-lg text-light m-1"
                                href="#!"
                                role="button"
                                data-mdb-ripple-color="dark"
                                ><i class="fab fa-twitter"></i
                            ></a>

                            <!-- Google -->
                            <a
                                class="btn btn-link btn-floating btn-lg text-light m-1"
                                href="#!"
                                role="button"
                                data-mdb-ripple-color="dark"
                                ><i class="fab fa-google"></i
                            ></a>

                            <!-- Instagram -->
                            <a
                                class="btn btn-link btn-floating btn-lg text-light m-1"
                                href="#!"
                                role="button"
                                data-mdb-ripple-color="dark"
                                ><i class="fab fa-instagram"></i
                            ></a>

                            <!-- Linkedin -->
                            <a
                                class="btn btn-link btn-floating btn-lg text-light m-1"
                                href="#!"
                                role="button"
                                data-mdb-ripple-color="dark"
                                ><i class="fab fa-linkedin"></i
                            ></a>
                            
                    </div>
                    </div>
                    
            </div>
            <div class="row">
            <p class="text-light text-center">© 2022 Fast Food. All rights reserved.</p></div>
        
    </footer>

app/views/layouts/_header.html.erb
<div class="container-fluid" id="banner">
    <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid d-flex p-0" >
    
        <div class="container">
            <a class="m-3" alt="brand-logo" href="<%= root_path %>">
              <%= image_tag "https://cdn-icons-png.flaticon.com/512/1980/1980788.png", id: 'logo', style:"width: 3rem"%> 
              </a>
              <a class="navbar-brand fw-bold fw-bold" href="<%= root_path%>">Fast Food</a>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <p> <% flash.each do |type, message| %>
                <div class="alert alert-info" role=alert >
                <%= type + "--" + message %>
                </div>
            <% end %> <p>

    <div class="container mr-5" style="width: 25em">
        <%= render 'searches/form' %>
    </div>



    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="btn btn-light-outline nav-link text-dark fw-bold" href="/">Home</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark fw-bold" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Recipes
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/recipes">View All</a></li>
                    <li><a class="dropdown-item" href="/recipes/new">Add New</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <%= link_to "Cooks", users_path, class: "btn btn-light-outline nav-link text-dark fw-bold"%>
            </li>
            <% if(user_signed_in?) %>
                <li class="nav-item">
                    <%# <a class="btn btn-light-outline nav-link text-dark fw-bold" href="users/dashboard_users">Profile</a> %>
                    <%= link_to "Profile", dashboard_user_path(current_user), class: "btn btn-light-outline nav-link text-dark fw-bold"%>
                </li>
                <li class="nav-item">
                    <div class="nav-link">
                    <%= button_to "Log out", session_path, method: :delete, class: "btn btn-danger" %></div>
                </li>
            <% else %>
                <li class="nav-item">

                   <a class="btn btn-light-outline nav-link text-dark fw-bold" href="<%= new_session_path%>">Sign In</a> 
                   <%#= link_to 'Sign In', new_session_path, class: "nav-link active nav_blue_line"%>

                </li>
                <li class="nav-item mx-2">
                    <a class="btn btn-light-outline nav-link text-dark fw-bold" href="<%= new_user_path %>">Sign Up </a>
                </li>
           <% end %>
        </ul>
        </div>
        </nav>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title> Fast Food </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "stars", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
   
   <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/1980/1980788.png">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    

  </head>
  <body>
      <%=render "layouts/header"  %>
      <%= yield %>
      <%= render "layouts/footer" %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>